/*****************************************************************//**
 * \file   TBBD_status.h
 * \brief  EXE return status.
 *
 * \author Yehuda Eisenberg
 * \date   September 2023
 *********************************************************************/


#pragma once

typedef enum tbbd_status_e {
	TBBD_STATUS_UNINITIALIZED = -1,
	TBBD_STATUS_SUCCESS = 0,

	TBBD_STATUS_LOAD_ICON_ERROR,
	TBBD_STATUS_CREATE_WINDOW_ERROR,
	TBBD_STATUS_CREATE_MUTEX_ERROR,
	TBBD_STATUS_THE_PROGRAM_ALREADY_OPEN,
	TBBD_STATUS_REGISTERCLASS_ERROR,
	TBBD_STATUS_LOAD_MENU_ERROR,
	TBBD_STATUS_FAILED_READ_VERSION,
	TBBD_STATUS_FAILED_WRITE_VERSION,
	TBBD_STATUS_FAILED_READ_LAST_UPDATE_DATE,
	TBBD_STATUS_FAILED_WRITE_LAST_UPDATE_DATE,
	TBBD_STATUS_WAMIN_WINHTTPOPEN_FAILED,
	TBBD_STATUS_WAMIN_WINHTTPCONNECT_FAILED,
	TBBD_STATUS_WAMIN_WINHTTPOPENREQUEST_FAILED,
	TBBD_STATUS_WAMIN_WINHTTPSENDREQUEST_FAILED,
	TBBD_STATUS_WAMIN_WINHTTPRECEIVERESPONSE_FAILED,
	TBBD_STATUS_WAMIN_WINHTTPQUERYDATAAVAILABLE_FAILED,
	TBBD_STATUS_HEAPALLOC_FAILED,
	TBBD_STATUS_WAMIN_WINHTTPREADDATA_FAILED,
	TBBD_STATUS_REGOPENKEYEXW_ERROR,
	TBBD_STATUS_REGQUERYVALUEEXW_ERROR,
	TBBD_STATUS_SHGETFOLDERPATHW_FAILED,
	TBBD_STATUS_CONFIG_DIR_PATH_IS_TOO_BIG,
	TBBD_STATUS_CREATEDIRECTORYW_FAILED,
	TBBD_STATUS_TBBD_FILE_PATH_IS_TOO_BIG,
	TBBD_STATUS_CONFIG_FILE_PATH_IS_TOO_BIG,
	TBBD_STATUS_DELETEFILEW_FAILED,
	TBBD_STATUS_URLDOWNLOADTOFILEW_FAILED,
	TBBD_STATUS_REGDELETEKEYW_ERROR,
	TBBD_STATUS_REGENUMKEYEXW_ERROR,
	TBBD_STATUS_REGSETVALUEEXW_ERROR,
	TBBD_STATUS_STOI_INVALID_ARGUMENT,
	TBBD_STATUS_STOI_OUT_OF_RANGE,
	TBBD_STATUS_GETMODULEHANDLEW_FAILED,
	TBBD_STATUS_FINDRESOURCEW_FAILED,
	TBBD_STATUS_LOADRESOURCE_FAILED,
	TBBD_STATUS_BAD_TEMP_PATH,
	TBBD_STATUS_CREATEFILEW_FAILED,
	TBBD_STATUS_WRITEFILE_FAILED,
	TBBD_STATUS_ERROR_ON_WRITE_TO_THE_FILE,
	TBBD_STATUS_CREATEPROCESSW_FAILED,
	TBBD_STATUS_REGEX_NOT_FOUND,
	TBBD_STATUS_GETMODULEFILENAMEW_FAILED,
	TBBD_STATUS_COPYFILEW_FAILED,
	TBBD_STATUS_ADAL_AND_LIVEID_REGEX_NOT_FOUND,
	TBBD_STATUS_STRINGCCHCOPYEXW_FAILED,
	TBBD_STATUS_CREATEFONTW_FAILED,
	TBBD_STATUS_CREATETHREAD_FAILED
} tbbd_status_t;
